services:
  postgres:
    build:
      context: ./database
      dockerfile: dockerfile
    container_name: datahub-postgres
    ports:
      - "31234:5432"
    env_file: .env
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./database/config/pg_hba.conf:/etc/postgresql/pg_hba.conf
    restart: unless-stopped
    networks:
      - datahub

  # datahub:
  #   read_only: true
  #   cap_drop:
  #   - ALL
  #   tmpfs:
  #   - /tmp
  #   build:
  #     context: ./datahub
  #     dockerfile: dockerfile
  #   ports:
  #     - "3000:3000"
  #   env_file: .env
  #   depends_on:
  #     - postgres
  #   restart: unless-stopped
  #   networks:
  #     - datahub
  #   deploy:
  #     replicas: 1
  #     resources:
  #       limits:
  #         cpus: '1'
  #         memory: 500M

volumes:
  postgres-data:

networks:
  datahub:
    driver: bridge