services:
  postgres:
    build:
      context: ./database
      dockerfile: dockerfile
    container_name: datahub-postgres
    ports:
      - "31234:5432"
    env_file: .env
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./database/config/pg_hba.conf:/etc/postgresql/pg_hba.conf
    restart: unless-stopped
    networks:
      - datahub

volumes:
  postgres-data:

networks:
  datahub:
    driver: bridge