services:
  postgres:
    image: postgres:17-alpine 
    # build:
      # context: ./database
      # dockerfile: dockerfile
    container_name: datahub-postgres
    ports:
      - "31234:5432"
    env_file: .env
    volumes:
      - postgres-data:/var/lib/postgresql/data
      # - ./database/config/postgresql.conf:/etc/postgresql/postgresql.conf
      - ./database/config/pg_hba.conf:/etc/postgresql/pg_hba.conf
      # - ./database/init/init.sql:/docker-entrypoint-initdb.d/init.sql
    # command: >
    #   postgres -c 'config_file=/etc/postgresql/postgresql.conf'
    restart: unless-stopped



volumes:
  postgres-data: